### ISSUE TITLE
[ERROR] GTK-CRITICAL Unable to Register the Application

### ISSUE THREAD

**Issue by Tamalero** [ilya-zlobintsev/LACT#414]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

After installing, it complained about the daemon not installed. Followed instructions and activated.

- App runs, no graphical glitches.
- Some content is not populated.
- Overclock, temps, etc.. cannot be modified and does not show any information.
 [
[LACT-sysfs-snapshot-20241115-070117.tar.gz](https://github.com/user-attachments/files/17777137/LACT-sysfs-snapshot-20241115-070117.tar.gz)
](url)]

Running from Konsole shows these errors:

(lact:21614): Gtk-WARNING **: 06:47:54.980: Unknown key gtk-modules in /etc/xdg/gtk-4.0/settings.ini
2024-11-15T14:47:55.058452Z  INFO lact_client::connection::unix: connecting to service at "/var/run/lactd.sock"

(lact:21614): Gtk-WARNING **: 06:47:55.082: gtk_window_set_titlebar() called on a realized window
 
(lact:21614): Gtk-CRITICAL **: 06:47:55.101: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:03.436: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:03.569: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:03.600: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:08.034: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:08.146: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:08.161: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 
(lact:21614): Gtk-CRITICAL **: 06:48:11.526: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
 

### System info

```markdown
- LACT version: 0.6.0 Fedora RPM.
- GPU model: MSI RTX 4090
- Kernel version: 6.11.7-201-fsync.FC40.86_64
- Distribution: Nobara 40
- Graphic Platform: Wayland
```

**Comment by ilya-zlobintsev** [comment]
Do you have the nvidia proprietary driver installed? The service couldn't find it:
```
libnvidia-ml.so: cannot open shared object file: No such file or directory
```

**Comment by Tamalero** [comment]
> Do you have the nvidia proprietary driver installed? The service couldn't find it:
> 
> ```
> libnvidia-ml.so: cannot open shared object file: No such file or directory
> ```
> 
> EDIT: you might also need CUDA installed: on Fedora it's the `xorg-x11-drv-nvidia-cuda-libs` package.

Hi!

Here is my nvidia-smi from NOBARA:

_```
Fri Nov 15 16:03:31 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        On  |   00000000:01:00.0  On |                  Off |
|  0%   55C    P0            104W /  480W |    7207MiB /  24564MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      4079      G   /usr/bin/kwalletd6                              6MiB |
|    0   N/A  N/A      4194      G   /usr/bin/kwin_wayland                         643MiB |
|    0   N/A  N/A      4299      G   /usr/bin/maliit-keyboard                      466MiB |
|    0   N/A  N/A      4306      G   /usr/bin/Xwayland                             104MiB |
|    0   N/A  N/A      4359      G   /usr/bin/ksmserver                              6MiB |
|    0   N/A  N/A      4361      G   /usr/bin/kded6                                  6MiB |
|    0   N/A  N/A      4393      G   /usr/bin/plasmashell                         1451MiB |
|    0   N/A  N/A      4411      G   /usr/libexec/kactivitymanagerd                  6MiB |
|    0   N/A  N/A      4479      G   /usr/bin/gmenudbusmenuproxy                     6MiB |
|    0   N/A  N/A      4480      G   /usr/bin/kaccess                                6MiB |
|    0   N/A  N/A      4483      G   ...6/polkit-kde-authentication-agent-1          6MiB |
|    0   N/A  N/A      4484      G   /usr/libexec/org_kde_powerdevil                 6MiB |
|    0   N/A  N/A      4485      G   /usr/libexec/xdg-desktop-portal-kde             6MiB |
|    0   N/A  N/A      4486      G   /usr/bin/xembedsniproxy                         6MiB |
|    0   N/A  N/A      4726      G   /usr/bin/kdeconnectd                            6MiB |
|    0   N/A  N/A      4867      G   /usr/bin/dolphin                                6MiB |
|    0   N/A  N/A      4886      G   /usr/bin/xwaylandvideobridge                    6MiB |
|    0   N/A  N/A      5386      G   ...yOnDemand --variations-seed-version        177MiB |
|    0   N/A  N/A      5583      G   ...local/share/Steam/ubuntu12_32/steam          8MiB |
|    0   N/A  N/A      6006      G   ./steamwebhelper                              105MiB |
|    0   N/A  N/A      6036      G   ....local/share/Steam/logs/cef_log.txt        487MiB |
|    0   N/A  N/A     12060      G   /app/lib/thunderbird/thunderbird              700MiB |
|    0   N/A  N/A     12235      G   /usr/lib64/firefox/firefox                   1764MiB |
|    0   N/A  N/A     13251      G   ...ve/brave --disable-frame-rate-limit          6MiB |
|    0   N/A  N/A     13294      G   ...1c8877394881fa8edec3c161bfbe12ef7d3        302MiB |
|    0   N/A  N/A     20401      G   /usr/libexec/baloorunner                        6MiB |
|    0   N/A  N/A     20409      G   /usr/bin/konsole                                6MiB |
+-----------------------------------------------------------------------------------------+
```_

It shows both the driver AND CUDA installed.

**Comment by ilya-zlobintsev** [comment]
I've tested this on a VM, and it looks like nobara packages the nvidia drivers in a weird way where the nvidia management library isn't available under its normal name. There was a bug report in btop having the same issue:
https://github.com/aristocratos/btop/issues/698

I've added a workaround for this in https://github.com/ilya-zlobintsev/LACT/commit/ebe3495cb5e1a2be29186053203f29a5ca461b01, it should work now with the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build).

**Comment by Tamalero** [comment]
> I've tested this on a VM, and it looks like nobara packages the nvidia drivers in a weird way where the nvidia management library isn't available under its normal name. There was a bug report in btop having the same issue: [aristocratos/btop#698](https://github.com/aristocratos/btop/issues/698)
> 
> I've added a workaround for this in [ebe3495](https://github.com/ilya-zlobintsev/LACT/commit/ebe3495cb5e1a2be29186053203f29a5ca461b01), it should work now with the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build).

Appreciate! Will install and inform you.

**Comment by Tamalero** [comment]
> I've tested this on a VM, and it looks like nobara packages the nvidia drivers in a weird way where the nvidia management library isn't available under its normal name. There was a bug report in btop having the same issue: [aristocratos/btop#698](https://github.com/aristocratos/btop/issues/698)
> 
> I've added a workaround for this in [ebe3495](https://github.com/ilya-zlobintsev/LACT/commit/ebe3495cb5e1a2be29186053203f29a5ca461b01), it should work now with the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build).

I seem to see all things populated now. Even when it complains about this...

![image](https://github.com/user-attachments/assets/deb2b9e2-22e4-4c69-ac5b-d32a9b3470f8)


[LACT-sysfs-snapshot-20241116-111235.tar.gz](https://github.com/user-attachments/files/17787702/LACT-sysfs-snapshot-20241116-111235.tar.gz)


Strangely I executed the recommended command. It runs fine but still get the popup error.

Otherwise, the app seems to work.
I get the charts, OC. The software shows the updated daemon.

By the way, I had an issue where it did not reboot the daemon automatically when reinstalling. So it complained that the daemon was mismatched. killed it then restarted the daemon and works.

**Comment by ilya-zlobintsev** [comment]
You seem to have overcomplicated the process quite a lot. There is no need to uninstall and reinstall to update, simply update the package and restart the service (`sudo systemctl restart lactd`). The debug snapshot shows that the daemon failed to start, likely because you've killed the daemon manually:
```
Nov 16 11:11:24 nobara-pc lact[63213]: Error: Socket "/var/run/lactd.sock" already exists. This probably means that another instance of lact-daemon is currently running. If you are sure that this is not the case, please remove the file
```
You can check this with `sudo systemctl status lactd`.

The information is populated and some options work because the GUI starts a local daemon as your user when it can't connect to a system one. It works for fetching information, but some options are only editable by root which means they only work when using the system service.

This should be fixed with a system reboot. It would clean up the leftover socket from when you killed the service, and the latest version of the daemon would start at boot.

Perhaps the daemon connection error should check if the service has failed though, to avoid confusion in situations like this.

**Comment by Tamalero** [comment]
> You seem to have overcomplicated the process quite a lot. There is no need to uninstall and reinstall to update, simply update the package and restart the service (`sudo systemctl restart lactd`). The debug snapshot shows that the daemon failed to start, likely because you've killed the daemon manually:
> 
> ```
> Nov 16 11:11:24 nobara-pc lact[63213]: Error: Socket "/var/run/lactd.sock" already exists. This probably means that another instance of lact-daemon is currently running. If you are sure that this is not the case, please remove the file
> ```
> 
> You can check this with `sudo systemctl status lactd`.
> 
> The information is populated and some options work because the GUI starts a local daemon as your user when it can't connect to a system one. It works for fetching information, but some options are only editable by root which means they only work when using the system service.
> 
> This should be fixed with a system reboot. It would clean up the leftover socket from when you killed the service, and the latest version of the daemon would start at boot.
> 
> Perhaps the daemon connection error should check if the service has failed though, to avoid confusion in situations like this.

Rebooted and Iḿ still getting these errors:


`(lact:8664): Gtk-WARNING **: 13:34:30.736: Unknown key gtk-modules in /etc/xdg/gtk-4.0/settings.ini
2024-11-16T21:34:30.826915Z  INFO lact_client::connection::unix: connecting to service at "/var/run/lactd.sock"

(lact:8664): Gtk-WARNING **: 13:34:30.854: gtk_window_set_titlebar() called on a realized window

(lact:8664): Gtk-CRITICAL **: 13:34:30.878: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:38.684: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:39.629: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:40.816: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:42.158: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:43.601: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:55.076: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:55.236: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:56.579: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:34:58.588: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed

(lact:8664): Gtk-CRITICAL **: 13:35:02.423: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'org.a11y.atspi.Registry': unit failed
`

![image](https://github.com/user-attachments/assets/35c5a029-fd58-44f8-8224-ebe9db3ab235)

The service seems to be working but some areas like the ADVANCED tab in OC still gives errors in the konsole.

**Comment by GloriousEggroll** [comment]
On Nobara try installing libnvidia-ml package:

libnvidia-ml-3:565.57.01-2.fc40.x86_64 : NVIDIA Management Library (NVML)
Repo        : nobara-appstream-40
Matched from:
Filename    : /usr/lib64/libnvidia-ml.so.1

(and 32 bit if needed)
libnvidia-ml-3:565.57.01-2.fc40.i686 : NVIDIA Management Library (NVML)
Repo        : nobara-appstream-40
Matched from:
Filename    : /usr/lib/libnvidia-ml.so.1

We follow negativo17's packaging, that's how it's packaged there:

https://github.com/negativo17/nvidia-driver/blob/e3d17abc4f0adb1dc4d11736a0d4bfe128b7b633/nvidia-driver.spec#L111

https://github.com/negativo17/nvidia-driver/blob/e3d17abc4f0adb1dc4d11736a0d4bfe128b7b633/nvidia-driver.spec#L459

**Comment by GloriousEggroll** [comment]
For libnvidia-ml.so install `cuda-nvml-devel`:
```
cuda-nvml-devel-1:12.5.82-1.fc40.x86_64 : Development files for the NVIDIA Management library (NVML)
Repo        : nobara-appstream-40
Matched from:
Filename    : /usr/lib64/libnvidia-ml.so
```

**Comment by GloriousEggroll** [comment]
I personally don't think this is correct on the negativo17 side and that the symlink should be part of libnvidia-ml, as that's how both arch and rpmfusion do it. I've opened an issue about it:
https://github.com/negativo17/cuda-nvml/issues/1

**Comment by ilya-zlobintsev** [comment]
Thanks @GloriousEggroll , the workaround for this isn't too difficult, but would be nice not to need it.

**Comment by scaronni** [comment]
We've removed the unversioned symlink also on the official CUDA nvidia driver: https://github.com/NVIDIA/yum-packaging-nvidia-driver/issues/9#issuecomment-2467474093

We checked internally the documentation and we couldn't find places where we're directing users to use the unversioned system library. Did you follow any instructions published by Nvidia on doing that?

**Comment by ilya-zlobintsev** [comment]
@scaronni 
> Did you follow any instructions published by Nvidia on doing that?

This wasn't done by any specific instruction, LACT uses a fork of the [nvml-wrapper](https://github.com/Cldfire/nvml-wrapper/) library which happened to load an unversioned library.

The [NVML API Reference](https://docs.nvidia.com/deploy/nvml-api/nvml-api-reference.html#nvml-api-reference) does mention the unversioned name:
```
On Linux the NVML library is named "libnvidia-ml.so" and can be found on the standard library path.
```
Perhaps this is where this came from? I Don't know for sure, as I wasn't the one who originally made the wrapper library.


Would it also be correct to always try to load `libnvidia-ml.so.1`, and not look for the unversioned symlink at all?

**Comment by scaronni** [comment]
Thanks, will follow up with the `nvml-wrapper` project as well!

**Comment by Tamalero** [comment]
Hi Folks, this collaboration is amazing but it still leaves me hanging.
Is there a solution to my problem? Note everything seems to work except the "advanced tab". 
As I cannot see the voltage control on my MSI 4090 RTX.

**Comment by ilya-zlobintsev** [comment]
@Tamalero there is no voltage control on nvidia currently, only GPU and VRAM clockspeed.

The `Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner` errors come from GTK itself because it is not able to register accessibility prompts. This seems to be related to your setup specifically, as I do not get those errors on a Nobara VM. They should not be critical to any LACT functionality though.

On your last screenshot everything seems correct. Is there something else that's wrong other than not being able to set a voltage?

**Comment by Tamalero** [comment]
> @Tamalero there is no voltage control on nvidia currently, only GPU and VRAM clockspeed.
> 
> The `Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner` errors come from GTK itself because it is not able to register accessibility prompts. This seems to be related to your setup specifically, as I do not get those errors on a Nobara VM. They should not be critical to any LACT functionality though.
> 
> On your last screenshot everything seems correct. Is there something else that's wrong other than not being able to set a voltage?

No.
Just some changes throws that same error even when things are applied.

And thank you. I was wondering if the voltage was available on nvidia.
Note I tried running it as sudo, still got these errors.

I might check with the Nobara team to see what is that error about.
