### ISSUE TITLE
Permission denied (os error 13) - Kubuntu Flatpak

### ISSUE THREAD

**Issue by stellaberrant** [ilya-zlobintsev/LACT#647]
### Checklist

- [x] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT/wiki/Hardware-Support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve on RDNA3/4 and missing fan control on laptops.
- [x] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration
- [x] I've checked that the issue still happens in the latest [development build](https://github.com/ilya-zlobintsev/lact?tab=readme-ov-file#development-builds).

### Bug description

After updating to 0.8, the daemon fails to start with an error message. I've tried rebooting the system, disabling and reenabling the daemon, and uninstalling and reinstalling the Flatpak. After I uninstalled the daemon completely, and a reboot, I got prompted to reinstall the daemon which I thought could fix this issue. However it's still the same afterwards

![Image](https://github.com/user-attachments/assets/4d2c3cf9-1708-493e-a94a-c730e360f3fa)
![Image](https://github.com/user-attachments/assets/9443f70f-5c88-472a-b3cc-183cb05907ff)

### System info

```markdown
- LACT version: 0.8
- GPU model: 7900 XT
- Kernel version:6.14.4-061404-generic (64-bit)
- Distribution: Kubuntu 25.04
```

**Comment by ilya-zlobintsev** [comment]
Please post the full service log from `journalctl -u lactd -e`

**Comment by stellaberrant** [comment]
here it is [lact_log.txt](https://github.com/user-attachments/files/20977064/lact_log.txt)

**Comment by SirBubbles** [comment]
Same experience here, under Manjaro. Attempting install via flatpak as well. Going to go back to the repo version for now. As nice as having profiles would be, I need a working version more.

**Comment by ilya-zlobintsev** [comment]
The log shows that the daemon fails to set the permissions for its socket, which is weird considering it runs as root and should be able to do that.

Unfortunately I'm not currently able to reproduce this - both updating from 0.7.4 and freshly installing 0.8.0 works correctly on Ubuntu and Linux Mint virtual machines.

**Comment by scotthva5** [comment]
Same exact issue here, fresh install of Ubuntu 24.04.2. I tried both flatpak and .deb, same result.

**Comment by nebadon2025** [comment]
> The log shows that the daemon fails to set the permissions for its socket, which is weird considering it runs as root and should be able to do that.
> 
> Unfortunately I'm not currently able to reproduce this - both updating from 0.7.4 and freshly installing 0.8.0 works correctly on Ubuntu and Linux Mint virtual machines.

I am experiencing the same issue on Kubuntu 25.04 with flatpak, this update has completely broken LACT on my machine.

**Comment by nebadon2025** [comment]
I also just tried the 24.04 deb on Kubuntu 25 and same exact  issue as flatpak.

**Comment by nebadon2025** [comment]
its possible this might be an issue with the mainline kernel, i rebooted back to the standard 6.11 kernel and it seemed to have fixed the problem, we are testing more now to see if this is indeed what fixed, even after going back to mainline kernel 6.15.4 it remains working for me now on the .deb, for some reason though seems like it needed to boot up once with stock kernel first, no clue why this would be the case though.

**Comment by nebadon2025** [comment]
update: we are unable to recreate switching to old kernel and fixing it, i can not explain how or why but all the sudden for me that one boot back to old kernel somehow fixed it, but @stellaberrant  wasn't able to reproduce that.

**Comment by stellaberrant** [comment]
I tried going back to the 6.11 kernel but it didn't fix the daemon unfortunately, and neither flatpak nor deb works for me even on old kernel

**Comment by ilya-zlobintsev** [comment]
~~This is very unlikely to be kernel related, what probably happened is that the deb version of the service started after a reboot.~~

~~Could you check if temporarily disabling apparmor allows the daemon to start?~~

~~sudo systemctl stop lactd~~
~~sudo rm /run/lactd.sock~~
~~sudo systemctl stop apparmor~~
~~sudo systemctl start lactd~~

~~I've additionally tried the flatpak on manjaro as well, also cannot reproduce the issue there.~~

**Comment by ilya-zlobintsev** [comment]
~~Here's how you can reset everything, maybe this helps someone get the service running:~~
- ~~Make sure only one version is installed at a time (e.g. only deb package or only flatpak)~~
- ~~`sudo systemctl disable --now lactd`~~
- ~~`sudo rm -r /etc/lact`~~
- ~~`sudo /etc/systemd/system/lactd.service`~~
- ~~(If flatpak) run the UI and let it perform the service setup~~
- ~~(If native package) `sudo systemctl enable --now lactd`~~

See comment below

**Comment by ilya-zlobintsev** [comment]
Update: I finally managed to reproduce this, it needed to be specifically a newer version of Kubuntu and not on a live iso

**Comment by ilya-zlobintsev** [comment]
For a temporary workaround, disabling apparmor allows the daemon to work: https://documentation.ubuntu.com/server/how-to/security/apparmor/#disabling-or-re-enabling-apparmor

Update: a less hacky workaround, that does not require disabling all of AppArmor:
```
sudo aa-complain /etc/apparmor.d/bwrap-userns-restrict 
```

For a more permanent solution a custom apparmor profile will have to be installed by the daemon install script, as currently some of the builtin ubuntu profiles are interacting with the service and forbidding it access. I'll try to find a solution and publish a hotfix to flathub when it's done.

**Comment by stellaberrant** [comment]
Thank you for the update and I'm glad you found the issue 💝

**Comment by ilya-zlobintsev** [comment]
A fix is up on flathub, an update and a reboot should resolve the problem.

**Comment by LauraBrosens** [comment]
Confirmed working on Linux Mint 22.1!

**Comment by stellaberrant** [comment]
It works on Kubuntu 25.04, thank you so much! 💝

**Comment by MechThumbs** [comment]
still doesn't work on Popos 24.04. keeps asking me to sudo systemctl enable --now lactd. same as the flatpak ver.

**Comment by 8836290** [comment]
Still does not work on Ubuntu 24.04 either. After update and reboot the message remains : 

Jul 02 15:30:37 LTS daemon.sh[5208]: /var/lib/flatpak/app/io.github.ilya_zlobintsev.LACT/x86_64/stable/active/files>
Jul 02 15:30:37 LTS systemd[1]: lactd.service: Main process exited, code=exited, status=127/n/a
Jul 02 15:30:37 LTS systemd[1]: lactd.service: Failed with result 'exit-code'.
Jul 02 15:30:38 LTS systemd[1]: lactd.service: Scheduled restart job, restart counter is at 5.
Jul 02 15:30:38 LTS systemd[1]: lactd.service: Start request repeated too quickly.
Jul 02 15:30:38 LTS systemd[1]: lactd.service: Failed with result 'exit-code'.
Jul 02 15:30:38 LTS systemd[1]: Failed to start lactd.service - GPU Control Daemon (via Flatpak).

**Comment by ilya-zlobintsev** [comment]
> Still does not work on Ubuntu 24.04 either. After update and reboot the message remains :
> 
> Jul 02 15:30:37 LTS daemon.sh[5208]: /var/lib/flatpak/app/io.github.ilya_zlobintsev.LACT/x86_64/stable/active/files> Jul 02 15:30:37 LTS systemd[1]: lactd.service: Main process exited, code=exited, status=127/n/a Jul 02 15:30:37 LTS systemd[1]: lactd.service: Failed with result 'exit-code'. Jul 02 15:30:38 LTS systemd[1]: lactd.service: Scheduled restart job, restart counter is at 5. Jul 02 15:30:38 LTS systemd[1]: lactd.service: Start request repeated too quickly. Jul 02 15:30:38 LTS systemd[1]: lactd.service: Failed with result 'exit-code'. Jul 02 15:30:38 LTS systemd[1]: Failed to start lactd.service - GPU Control Daemon (via Flatpak).

Please post a full log, this is truncated.

**Comment by 8836290** [comment]
Here you go : 

[Jul 02 15 30 37 LTS systemd.txt](https://github.com/user-attachments/files/21022783/Jul.02.15.30.37.LTS.systemd.txt)

**Comment by ilya-zlobintsev** [comment]
Update: I managed to reproduce this in a VM, this is a different issue from the original one, and is caused by the dbus packaging apparently being different specifically on 24.04. With https://github.com/ilya-zlobintsev/LACT/commit/f6c8e85d146fa979c232b887885069bc0146e7e3 the launch script has been changed to use a generic command that's present on every system. 
The update will be up on flathub soon.

Edit: Update is up now.

**Comment by MechThumbs** [comment]
Thank you just got the update! and its working! how does one support you? this app is the best out there.

**Comment by ilya-zlobintsev** [comment]
> Thank you just got the update! and its working! how does one support you? this app is the best out there.

Thanks, you can use the sponsor button on github on the repo page, it has links to ko-fi and liberapay.

**Comment by 8836290** [comment]
LACT works fine now on Ubuntu 24.04.
